# https://docs.helix-editor.com/configuration.html
theme = "dracula_at_night"

[editor]
rulers = [80, 120]
line-number = "relative"
mouse = false
auto-completion = true
auto-info = true
bufferline = "multiple"

[editor.indent-guides]
render = true
character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# Use system clipboard
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
# Move line up or down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"] 